apiVersion: apps/v1
kind: Deployment                                         
metadata:
  name: scaletestapp-depl
spec:
  replicas: 1         
  selector:
    matchLabels:
      app: scaletestapp
  template:                                               
    metadata:
      labels:
        app: scaletestapp
    spec:                                                
      containers:
        - image: shestera/scaletestapp
          name: scaletestapp                            
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "30Mi"