apiVersion: v1
kind: Service              
metadata:
  name: scaletestapp-svc
spec:
  type: LoadBalancer       
  ports:
  - port: 8080           
    protocol: TCP         
    targetPort: 8080 
  selector:               
    app: scaletestapp      